# Generated by Django 2.1.7 on 2019-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
