# Generated by Django 2.1.7 on 2019-03-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0005_clog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='stamp',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
